title: almendra # name of the site
author: almond Heil # name of site's author
email: contact@almendra.dev # email of site's author
url: https://almondheil.github.io
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if your site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  a website where I'm going to put whatever I feel like. right now,
  it has things I've learned, art, and projects I enjoyed :)

markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [no_auto_typographic]

permalink: /:categories/:slug # simplify urls

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

remote_theme: no-style-please # remote_theme is needed when hosting on github pages

source: source

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
